import base64
import os
import time
from pathlib import Path
from typing import Any

import requests


class DoubaoMediaProvider:
    """Volcengine Ark provider using Seedream for images and Seedance for I2V.

    Seedream URL responses are cached beside each generated keyframe so Seedance can reuse
    the provider-hosted image as a first frame. If a keyframe was not generated by Doubao,
    regenerate it with MEDIA_PROVIDER=doubao before requesting Seedance I2V.
    """

    def __init__(self) -> None:
        self.api_key = os.getenv("ARK_API_KEY", "").strip()
        if not self.api_key:
            raise RuntimeError("ARK_API_KEY is required for MEDIA_PROVIDER=doubao")
        self.base_url = os.getenv(
            "ARK_BASE_URL", "https://ark.cn-beijing.volces.com/api/v3"
        ).rstrip("/")
        self.image_model = os.getenv(
            "DOUBAO_IMAGE_MODEL", "doubao-seedream-5-0-lite-260128"
        )
        self.video_model = os.getenv(
            "DOUBAO_VIDEO_MODEL", "doubao-seedance-1-5-pro-251215"
        )
        self.image_size = os.getenv("DOUBAO_IMAGE_SIZE", "2K")
        self.video_duration = int(os.getenv("DOUBAO_VIDEO_DURATION", "5"))
        self.video_ratio = os.getenv("DOUBAO_VIDEO_RATIO", "9:16")
        self.poll_seconds = int(os.getenv("DOUBAO_POLL_SECONDS", "8"))
        self.max_wait_seconds = int(os.getenv("DOUBAO_MAX_WAIT_SECONDS", "900"))
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            }
        )

    @staticmethod
    def _reference_b64(path: str | Path) -> str:
        return base64.b64encode(Path(path).read_bytes()).decode("ascii")

    @staticmethod
    def _url_sidecar(path: str | Path) -> Path:
        path = Path(path)
        return path.with_suffix(path.suffix + ".source_url")

    def _remember_source_url(self, path: str | Path, url: str) -> None:
        self._url_sidecar(path).write_text(url, encoding="utf-8")

    def _source_url(self, path: str | Path) -> str:
        sidecar = self._url_sidecar(path)
        if not sidecar.exists():
            raise RuntimeError(
                f"Doubao I2V requires a Seedream-hosted first-frame URL. Missing {sidecar}. "
                "Regenerate the approved keyframe with MEDIA_PROVIDER=doubao, then generate motion."
            )
        url = sidecar.read_text(encoding="utf-8").strip()
        if not url:
            raise RuntimeError(f"Empty Seedream source URL sidecar: {sidecar}")
        return url

    def generate_image(
        self,
        prompt: str,
        output_path: str | Path,
        *,
        reference_images: list[str | Path] | None = None,
    ) -> Path:
        body: dict[str, Any] = {
            "model": self.image_model,
            "prompt": prompt,
            "size": self.image_size,
            "response_format": "url",
            "watermark": False,
        }
        refs = reference_images or []
        if refs:
            body["image"] = [self._reference_b64(p) for p in refs]

        response = self.session.post(
            f"{self.base_url}/images/generations",
            json=body,
            timeout=300,
        )
        response.raise_for_status()
        payload = response.json()
        data = payload.get("data") or []
        if not data:
            raise RuntimeError(f"Seedream returned no image data: {payload}")

        item = data[0]
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        url = item.get("url")
        if url:
            image_response = requests.get(url, timeout=180)
            image_response.raise_for_status()
            output_path.write_bytes(image_response.content)
            self._remember_source_url(output_path, str(url))
            return output_path

        b64 = item.get("b64_json")
        if b64:
            output_path.write_bytes(base64.b64decode(b64))
            return output_path
        raise RuntimeError(f"Seedream image item has neither url nor b64_json: {item}")

    def _create_video_task(self, prompt: str, first_frame_url: str) -> str:
        text = f"{prompt} --ratio {self.video_ratio} --dur {self.video_duration}"
        body = {
            "model": self.video_model,
            "content": [
                {"type": "text", "text": text},
                {
                    "type": "image_url",
                    "image_url": {"url": first_frame_url},
                    "role": "first_frame",
                },
            ],
        }
        response = self.session.post(
            f"{self.base_url}/contents/generations/tasks",
            json=body,
            timeout=60,
        )
        response.raise_for_status()
        payload = response.json()
        task_id = payload.get("id")
        if not task_id:
            raise RuntimeError(f"Seedance task creation returned no id: {payload}")
        return str(task_id)

    def _wait_video(self, task_id: str) -> str:
        deadline = time.time() + self.max_wait_seconds
        while time.time() < deadline:
            response = self.session.get(
                f"{self.base_url}/contents/generations/tasks/{task_id}",
                timeout=60,
            )
            response.raise_for_status()
            payload = response.json()
            status = payload.get("status")
            if status == "succeeded":
                url = (payload.get("content") or {}).get("video_url")
                if not url:
                    raise RuntimeError(f"Seedance succeeded without video_url: {payload}")
                return str(url)
            if status in {"failed", "cancelled"}:
                raise RuntimeError(
                    f"Seedance task {task_id} ended with status={status}: {payload.get('error')}"
                )
            time.sleep(self.poll_seconds)
        raise TimeoutError(f"Seedance task timed out after {self.max_wait_seconds}s: {task_id}")

    def generate_video(
        self,
        prompt: str,
        input_image: str | Path,
        output_path: str | Path,
    ) -> Path:
        task_id = self._create_video_task(prompt, self._source_url(input_image))
        video_url = self._wait_video(task_id)
        response = requests.get(video_url, timeout=300)
        response.raise_for_status()
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_bytes(response.content)
        return output_path
